name: Build binaries

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-linux:
    name: Build binaries
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: go build -o failtorun FailToRun.go
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: failtorun
          path: ./failtorun
  build-windows:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: go build -o FailToRun.exe FailToRun.go
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FailToRun.exe
          path: ./FailToRun.exe
